version: '3.1'

services:

  redmine-app:
    image: redmine
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: redmine-app
    restart: unless-stopped
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: redmine_key_base
    volumes:
       - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
       - ./crontab:/usr/src/redmine/crontab
       - ./cronjob.sh:/usr/src/redmine/cronjob.sh
       - ./volumes/redmine/logs:/usr/src/redmine/log
       - ./volumes/redmine/files:/usr/src/redmine/files
    networks:
      db_net:
      api_net:
    links:
      - redmine_db:db

  redmine_db:
    image: mysql:5.7
    container_name: redmine-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes: 
      - ./volumes/redmine/mysql/:/var/lib/mysql/
    networks:
      db_net:

networks:
  api_net:
    external:
        name: api_net
  db_net:
    external:
        name: db_net

